// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/leagues/:leagueAbbrev/:year": {
    params: {
      "leagueAbbrev": string;
      "year": string;
    };
  };
  "/teams/:teamId/:year": {
    params: {
      "teamId": string;
      "year": string;
    };
  };
  "/players/:playerId": {
    params: {
      "playerId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/leagues/:leagueAbbrev/:year" | "/teams/:teamId/:year" | "/players/:playerId";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/leagues.$leagueAbbrev.$year.tsx": {
    id: "routes/leagues.$leagueAbbrev.$year";
    page: "/leagues/:leagueAbbrev/:year";
  };
  "routes/teams.$teamId.$year.tsx": {
    id: "routes/teams.$teamId.$year";
    page: "/teams/:teamId/:year";
  };
  "routes/players.$playerId.tsx": {
    id: "routes/players.$playerId";
    page: "/players/:playerId";
  };
};

type RouteModules = {
  "root": typeof import("./src/web/root.tsx");
  "routes/_index": typeof import("./src/web/routes/_index.tsx");
  "routes/leagues.$leagueAbbrev.$year": typeof import("./src/web/routes/leagues.$leagueAbbrev.$year.tsx");
  "routes/teams.$teamId.$year": typeof import("./src/web/routes/teams.$teamId.$year.tsx");
  "routes/players.$playerId": typeof import("./src/web/routes/players.$playerId.tsx");
};